db.host=localhost
db.port=3306
db.user=root
db.password=
db.dbname=langla_acc
db.dbData=langla_data
server.debug=false
mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=admin
mongodb.user=root
mongodb.password=
#game.event= com.event.Summer
#game.event = com.event.GioTo
game.event = com.event.Halloween